version: '3.8'
services:
  k6:
    build: .
    # Si quieres correr un test específico, descomenta la línea de abajo y cambia 'base.js'
    # command: run /app/tests/load.js
    volumes:
      # Sincroniza tu carpeta local con el contenedor para que no necesites 
      # hacer rebuild del contenedor cada vez que modificas un script local
      - .:/app
