name: K6 API Performance Tests Matrix example

on:
  push:
    branches: [ "trunk","feature/**" ] 

jobs:
  test-parallel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Para que si una falla, las demás sigan
      matrix:
        script: [ 'tests/base.js', 'tests/load.js', 'tests/base.js' ]  

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: build docker image
        run:  docker build -t k6image .

      - name: Run Docker Image
        run: docker run --rm -it -v ${PWD}:/app -w /app k6image run  ${{matrix.script}}

